#! /bin/bash

# Definitions of needed functions
section () {
	# This function prints the name of the current running section in a different color
	# Useful for debugging and tracing
	tput setaf 1
	echo $1
	tput sgr0
}

Error () {
	# Function used to print errors (same as section but different color to indicate errors)
	tput setaf 4
	echo $1
	tput sgr0
	exit 1
}
################### End Of Functions ###################
# set -e makes the script exit immediately if any error occurs
set -e

# This script must be run from within PINTOSHOME
PINTOSHOME="$(pwd)"

section "GDBMACROS"
sed -i "s+GDBMACROS=/usr/class/cs140/pintos/pintos/src/misc/gdb-macros+GDBMACROS=$PINTOSHOME/src/misc/gdb-macros+" $PINTOSHOME/src/utils/pintos-gdb

section "Compile the Utilities, and ignore any warnings"
cd $PINTOSHOME/src/utils
make

section "Point to qemu in pintos perl script"
old='$sim = "bochs" if !defined $sim;'
new='$sim = "qemu" if !defined $sim;'
sed -i "s+$old+$new+" $PINTOSHOME/src/utils/pintos


# set +e does the opposit of set -e
# this is needed to revert bash to its original state before the script started
set +e
